export const cropsData = [
  {
    slug: "vanilla",
    name: "Vanilla",
    tagline: "The Green Gold of Sri Lanka",
    color: "#D4AF37",
    accentColor: "#004d4d",
    heroImage:
      "/images/slides/home-bg-2.webp",
    icon: "fa-leaf",
    description:
      "Vanilla is one of the world's most prized spices, and Sri Lanka's tropical climate provides the perfect conditions for cultivating premium-grade vanilla beans. Agroventures manages every stage - from planting and hand pollination to curing and export - ensuring the highest quality product.",
    highlights: [
      { icon: "fa-sun", label: "Tropical Climate", value: "Ideal growing conditions year-round" },
      { icon: "fa-clock", label: "Harvest Cycle", value: "9–12 months after pollination" },
      { icon: "fa-globe", label: "Export Markets", value: "Europe, USA, Middle East" },
      { icon: "fa-money-bill", label: "Market Value", value: "One of the highest-value spices globally" },
    ],
    process: [
      { step: "01", title: "Land Preparation", desc: "Soil enrichment, fencing, and shade structure installation." },
      { step: "02", title: "Planting", desc: "Vanilla vines planted on support trees with organic compost." },
      { step: "03", title: "Hand Pollination", desc: "Each flower is hand-pollinated to ensure maximum yield." },
      { step: "04", title: "Harvesting", desc: "Beans harvested at peak maturity for optimal flavour." },
      { step: "05", title: "Curing & Processing", desc: "Traditional curing process to develop the signature aroma." },
      { step: "06", title: "Export", desc: "Packaged and exported to international premium markets." },
    ],
  },
  {
    slug: "cinnamon",
    name: "Cinnamon",
    tagline: "Ceylon's Finest Spice",
    color: "#8B4513",
    accentColor: "#004d4d",
    heroImage:
      "https://pub-8476bede5a4146e8b7731cfe515f1c3b.r2.dev/av-plantations/Website/crops/cinnamon.jpg",
    icon: "fa-seedling",
    description:
      "Ceylon Cinnamon - known as 'true cinnamon' - is native to Sri Lanka and is globally recognised for its delicate, sweet flavour and superior quality. Agroventures cultivates and processes Ceylon Cinnamon using traditional methods passed down through generations, ensuring authenticity and premium grade.",
    highlights: [
      { icon: "fa-star", label: "Grade", value: "Ceylon True Cinnamon (C. verum)" },
      { icon: "fa-clock", label: "Harvest Cycle", value: "Every 2 years after initial growth" },
      { icon: "fa-globe", label: "Export Markets", value: "Europe, USA, Japan" },
      { icon: "fa-certificate", label: "Certification", value: "Organic & GI certified" },
    ],
    process: [
      { step: "01", title: "Cultivation", desc: "Cinnamon trees grown in well-drained sandy soil." },
      { step: "02", title: "Coppicing", desc: "Stems cut close to the ground to encourage new shoots." },
      { step: "03", title: "Peeling", desc: "Outer bark removed and inner bark carefully peeled." },
      { step: "04", title: "Rolling", desc: "Inner bark rolled into quills by skilled artisans." },
      { step: "05", title: "Drying", desc: "Quills dried in shade to preserve aroma and colour." },
      { step: "06", title: "Grading & Export", desc: "Sorted by grade and exported to global markets." },
    ],
  },
  {
    slug: "pepper",
    name: "Pepper",
    tagline: "The King of Spices",
    color: "#2d3e1f",
    accentColor: "#004d4d",
    heroImage:
      "https://pub-8476bede5a4146e8b7731cfe515f1c3b.r2.dev/av-plantations/Website/crops/pepper.jpg",
    icon: "fa-circle",
    description:
      "Black pepper is one of the most traded spices in the world. Sri Lanka's highland climate produces pepper with a bold, complex flavour profile. Agroventures cultivates both black and white pepper varieties, managing the full supply chain from vine to export.",
    highlights: [
      { icon: "fa-leaf", label: "Varieties", value: "Black Pepper & White Pepper" },
      { icon: "fa-clock", label: "Harvest Cycle", value: "Annual harvest" },
      { icon: "fa-globe", label: "Export Markets", value: "Worldwide" },
      { icon: "fa-chart-bar", label: "Yield", value: "High yield per hectare" },
    ],
    process: [
      { step: "01", title: "Planting", desc: "Pepper vines planted on support poles or trees." },
      { step: "02", title: "Training", desc: "Vines trained upward for optimal sunlight exposure." },
      { step: "03", title: "Harvesting", desc: "Berries harvested when partially ripe for black pepper." },
      { step: "04", title: "Processing", desc: "Berries dried in sun for black pepper or soaked for white." },
      { step: "05", title: "Cleaning", desc: "Cleaned and sorted by size and quality." },
      { step: "06", title: "Export", desc: "Packed and shipped to international buyers." },
    ],
  },
  {
    slug: "cardamom",
    name: "Cardamom",
    tagline: "The Queen of Spices",
    color: "#4E7942",
    accentColor: "#004d4d",
    heroImage: "https://pub-8476bede5a4146e8b7731cfe515f1c3b.r2.dev/av-plantations/Website/crops/cardamom.jpg",
    icon: "fa-apple-whole",
    description:
      "Cardamom, celebrated as the 'Queen of Spices', is a highly aromatic pod crop prized for its intense, complex flavour. Agroventures cultivates cardamom in Sri Lanka's cool, high-altitude regions, carefully managing every stage from planting to curing to produce premium-grade green pods for global markets.",
    highlights: [
      { icon: "fa-leaf", label: "Variety", value: "Green Cardamom (Elettaria cardamomum)" },
      { icon: "fa-clock", label: "Harvest Cycle", value: "2–3 years to first harvest" },
      { icon: "fa-globe", label: "Export Markets", value: "Middle East, Europe, Asia" },
      { icon: "fa-money-bill", label: "Market Value", value: "Among the most expensive spices by weight" },
    ],
    process: [
      { step: "01", title: "Land Preparation", desc: "Shaded, well-drained highland soil prepared with organic matter." },
      { step: "02", title: "Planting", desc: "Rhizomes planted under natural forest canopy for ideal shade." },
      { step: "03", title: "Flowering & Pollination", desc: "Ground-level panicles flower and are naturally pollinated." },
      { step: "04", title: "Harvesting", desc: "Pods hand-picked individually as each one ripens." },
      { step: "05", title: "Curing & Drying", desc: "Pods carefully dried to preserve colour and aroma." },
      { step: "06", title: "Grading & Export", desc: "Sorted by size and colour, then packed for export." },
    ],
  },
  {
    slug: "nutmeg",
    name: "Nutmeg",
    tagline: "Aromatic Spice of the Tropics",
    color: "#A0522D",
    accentColor: "#004d4d",
    heroImage: "https://pub-8476bede5a4146e8b7731cfe515f1c3b.r2.dev/av-plantations/Website/crops/nutmeg.jpg",
    icon: "fa-seedling",
    description:
      "Nutmeg is a highly aromatic spice native to the Banda Islands, but Sri Lanka's climate allows for successful cultivation. Agroventures manages nutmeg plantations with a focus on sustainable practices, ensuring high-quality spice production for both local and international markets.",
    highlights: [
      { icon: "fa-leaf", label: "Varieties", value: "Nutmeg & Mace" },
      { icon: "fa-clock", label: "Harvest Cycle", value: "3–4 years to first harvest" },
      { icon: "fa-globe", label: "Export Markets", value: "Europe, USA, Middle East" },
      { icon: "fa-certificate", label: "Certification", value: "Organic & Fair Trade" },
    ],
    process: [
      { step: "01", title: "Planting", desc: "Nutmeg trees planted in well-drained soil." },
      { step: "02", title: "Maintenance", desc: "Regular pruning and organic fertilisation." },
      { step: "03", title: "Flowering & Pollination", desc: "Natural pollination leads to fruit development." },
      { step: "04", title: "Harvesting", desc: "Fruits harvested when mature for nutmeg and mace." },
      { step: "05", title: "Processing", desc: "Nutmeg seeds dried and mace separated from the aril." },
      { step: "06", title: "Export", desc: "Packed and shipped to international spice markets." },
    ],
  },
  {
    slug: "vegetables",
    name: "Vegetables",
    tagline: "Fresh From the Field",
    color: "#27ae60",
    accentColor: "#004d4d",
    heroImage:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1400&q=80",
    icon: "fa-seedling",
    description:
      "Seasonal vegetables are cultivated on Agroventures land to support local food security and generate additional revenue. Crops include ginger, turmeric, leafy greens, and root vegetables - all grown using sustainable, chemical-free practices.",
    highlights: [
      { icon: "fa-leaf", label: "Varieties", value: "Ginger, Turmeric, Leafy Greens" },
      { icon: "fa-clock", label: "Harvest Cycle", value: "Seasonal rotations" },
      { icon: "fa-heart", label: "Practices", value: "Chemical-free, organic" },
      { icon: "fa-house", label: "Market", value: "Local communities & export" },
    ],
    process: [
      { step: "01", title: "Soil Preparation", desc: "Deep tilling and organic compost application." },
      { step: "02", title: "Planting", desc: "Seeds and seedlings planted in seasonal rotations." },
      { step: "03", title: "Irrigation", desc: "Drip irrigation to conserve water." },
      { step: "04", title: "Pest Management", desc: "Natural pest control methods applied." },
      { step: "05", title: "Harvesting", desc: "Hand-harvested at optimal maturity." },
      { step: "06", title: "Supply", desc: "Distributed to local markets and processing units." },
    ],
  },
  {
    slug: "cloves",
    name: "Cloves",
    tagline: "The Spice of Life",
    color: "#5C3A21",
    accentColor: "#004d4d",
    heroImage: "https://pub-8476bede5a4146e8b7731cfe515f1c3b.r2.dev/av-plantations/Website/crops/cloves.jpg",
    icon: "fa-seedling",
    description:
      "Cloves are the dried aromatic flower buds of the clove tree, prized worldwide for their warm, pungent flavour and rich fragrance. Agroventures cultivates clove trees across Sri Lanka's humid tropical lowlands, hand-harvesting and sun-drying each bud to preserve its signature oil-rich aroma.",
    highlights: [
      { icon: "fa-leaf", label: "Variety", value: "Syzygium aromaticum" },
      { icon: "fa-clock", label: "Harvest Cycle", value: "Twice yearly, after 4–6 years maturity" },
      { icon: "fa-globe", label: "Export Markets", value: "India, Middle East, Europe" },
      { icon: "fa-certificate", label: "Grade", value: "Hand-picked premium buds" },
    ],
    process: [
      { step: "01", title: "Cultivation", desc: "Clove trees grown in humid, well-drained tropical soil." },
      { step: "02", title: "Flower Bud Formation", desc: "Unopened aromatic flower buds develop in clusters." },
      { step: "03", title: "Hand Harvesting", desc: "Buds hand-picked at the right stage, before flowering." },
      { step: "04", title: "Sun Drying", desc: "Buds sun-dried until deep brown and oil-rich." },
      { step: "05", title: "Cleaning & Sorting", desc: "Dried cloves cleaned and graded by size." },
      { step: "06", title: "Export", desc: "Packed and shipped to international spice markets." },
    ],
  },
];